### ISSUE TITLE
#Enhancement Request : need to set a download path

### ISSUE THREAD

**Issue by rubinnellikunnathu** [esafirm/RxDownloader#11]
I need to download a particular item from url and i need to save it in specific directory.
Ex: i need to download files folder like music or images or downloads ..

please help .

**Comment by esafirm** [comment]
@rubinnellikunnathu you can use `DownloadManager.Request` directly. 

ex: 
```
DownloadManager.Request request = new DownloadManager.Request(downloadUri);
request.setDestinationInExternalPublicDir(Environment.DIRECTORY_MOVIES, filename)

RxDownloadManager.getInstance(context).download(request)
```
