### ISSUE TITLE
RxJava2 support?

### ISSUE THREAD

**Issue by Kisty** [esafirm/RxDownloader#14]
Hi there! 
I'd like support for RxJava2 support. I may go ahead and try and port this library to RxJava2 if that's OK. Would you be interested?

**Comment by Kisty** [comment]
Ah, looks like it's already done in this fork 😄 https://github.com/VladislavNikolaev/RxDownloader

**Comment by esafirm** [comment]
Well i'm always open to pull request
As you can see, most of the code is from 2015 when my understanding of Rx still limited. 
Maybe it's time to upgrade? 😃

**Comment by Kisty** [comment]
Indeed! Not sure how to do a pull request from a repo which isn't mine. @VladislavNikolaev, can you do so?

**Comment by VladislavNikolaev** [comment]
Yes, i will try.

Here it is 👍 
https://github.com/esafirm/RxDownloader/pull/15

**Comment by esafirm** [comment]
v.2.0.0 is released now with RxJava2 support.
